// <auto-generated />
using System;
using FeedbackService.Repo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeedbackService.Repo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FeedbackService.Repo.EntityFramework.Entities.EnumFeedbackRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FeedbackRating","Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HappyFace"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SadFace"
                        });
                });

            modelBuilder.Entity("FeedbackService.Repo.EntityFramework.Entities.EnumRequestRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestRoles","Lookup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Requestor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Recipient"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Volunteer"
                        },
                        new
                        {
                            Id = 4,
                            Name = "GroupAdmin"
                        });
                });

            modelBuilder.Entity("FeedbackService.Repo.EntityFramework.Entities.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("FeedbackDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<byte>("FeedbackRatingTypeId")
                        .HasColumnName("FeedbackRatingTypeID")
                        .HasColumnType("tinyint");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<byte>("RequestRoleTypeId")
                        .HasColumnName("RequestRoleTypeID")
                        .HasColumnType("tinyint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedback","Feedback");
                });
#pragma warning restore 612, 618
        }
    }
}
